# Pandas: Series

In [4]:
import pandas as pd
sales = pd.Series([100,200,100,400])
print(sales)
print('---------------')
print(sales.values)
print(sales.index)

0    100
1    200
2    100
3    400
dtype: int64
---------------
[100 200 100 400]
RangeIndex(start=0, stop=4, step=1)


In [5]:
sales= pd.Series([100,200,100,400], index=['Jan','Feb','Mar','Apr'])
print(sales)
print('----------------')
print(sales.values)
print(sales.index)

Jan    100
Feb    200
Mar    100
Apr    400
dtype: int64
----------------
[100 200 100 400]
Index(['Jan', 'Feb', 'Mar', 'Apr'], dtype='object')


In [10]:
monthNames= ['Jan','Feb','Mar','Apr']
sales = pd.Series([100.,200.,100.,400.], index=['Jan','Feb','Mar','Apr'], name="4 month sales")
#both are same
saless = pd.Series([100,200,100,400], index=monthNames, name="4 month sales")
print(sales)
print(saless)
print(saless.values)

Jan    100.0
Feb    200.0
Mar    100.0
Apr    400.0
Name: 4 month sales, dtype: float64
Jan    100
Feb    200
Mar    100
Apr    400
Name: 4 month sales, dtype: int64
[100 200 100 400]


In [14]:
kantine=pd.Series([25,40,10,71,50], index=['Mon','Tues','Wed','Thur','Fri'], name="Sandwidthes in Week ")
print(kantine)
print(kantine['Tues'])

Mon     25
Tues    40
Wed     10
Thur    71
Fri     50
Name: Sandwidthes in Week , dtype: int64
40


In [23]:
import calendar
month = calendar.calendar(2016)
print(month)


                                  2016

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
             1  2  3       1  2  3  4  5  6  7          1  2  3  4  5  6
 4  5  6  7  8  9 10       8  9 10 11 12 13 14       7  8  9 10 11 12 13
11 12 13 14 15 16 17      15 16 17 18 19 20 21      14 15 16 17 18 19 20
18 19 20 21 22 23 24      22 23 24 25 26 27 28      21 22 23 24 25 26 27
25 26 27 28 29 30 31      29                        28 29 30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
             1  2  3                         1             1  2  3  4  5
 4  5  6  7  8  9 10       2  3  4  5  6  7  8       6  7  8  9 10 11 12
11 12 13 14 15 16 17       9 10 11 12 13 14 15      13 14 15 16 17 18 19
18 19 20 21 22 23 24      16 17 18 19 20 21 22      20 21 22 23 24 25 26
25 26 27 28 29 30         23 24 25 


# Create a pandas series to store a canteen data to hold values of how many sandwithes are sold each days(one week)

In [29]:
import numpy as np
import calendar
values = np.random.randint(10,101, size =[12])
months = []
for i in range(1,13):
    mnth = calendar.month_name[i]
    months.append(mnth)
    
sw=pd.Series(values, index= months)
print(sw)

January       10
February      13
March         84
April         53
May           74
June          59
July          30
August        24
September     73
October      100
November      96
December      48
dtype: int32


In [31]:
print(sw[['March','July']])

March    84
July     30
dtype: int32


In [32]:
sdata = {"Sindh": 35000, "Punjab":45000, "KPK":30000, "Balochistan": 20000}
tax_by_state = pd.Series(sdata, index = ['Punjab','Sindh','KPK','Balochistan','GB'])
print(tax_by_state)
print(pd.isnull(tax_by_state))

Punjab         45000.0
Sindh          35000.0
KPK            30000.0
Balochistan    20000.0
GB                 NaN
dtype: float64
Punjab         False
Sindh          False
KPK            False
Balochistan    False
GB              True
dtype: bool


In [ ]:
sdata = {"Sindh": 35000, "Punjab":45000, "KPK":30000, "Balochistan": 20000}

tax_by_state = pd.Series(list(sdata.values()),
                         index

In [1]:
import pandas as pd

apples = pd.Series([3,2,0,1])
oranges = pd.Series([3,4,7,8])

data = {"apples": apples, "oranges":oranges}
fruits_df=pd.DataFrame(data)
print(fruits_df)

   apples  oranges
0       3        3
1       2        4
2       0        7
3       1        8


In [ ]:
frame2 = pd.DataFrame(data, columns=[100,200,300,400], index =[10,20,30,40])
frame2.head()