In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.1.0-dev20191128'

In [6]:
hello = tf.constant('Hello') # constant is use to print string in tf
world = tf.constant('World')
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello'>

In [4]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [5]:
print(hello)

tf.Tensor(b'Hello', shape=(), dtype=string)


In [16]:
with tf.compat.v1.Session(s) as sess:
    result = sess.run(hello)
    result = s

NameError: name 's' is not defined

In [11]:
print(result)

NameError: name 'result' is not defined

In [19]:
var1 = tf.constant(10)
var2 = tf.constant(30)
var1 + var2

<tf.Tensor: shape=(), dtype=int32, numpy=40>

In [2]:
fill=tf.fill((5,5),10)

In [3]:
zero = tf.zeros((5,5))

In [5]:
normal = tf.random_normal_initializer((4,4))

In [6]:
lst=[fill,zero,normal]

In [8]:
sess=tf.compat.v1.InteractiveSession()
for op in lst:
    print(op)

tf.Tensor(
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]], shape=(5, 5), dtype=int32)
tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(5, 5), dtype=float32)


C:\Users\tehse\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py:1752: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [9]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[10],[100]])
display(a)
display(b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 10],
       [100]])>

In [10]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[210],
       [430]])>

# Exercise 2

In [11]:
var1 = tf.constant(10)
var2 = tf.constant(20)
var3 = var1 + var2

In [12]:
print(var3)

tf.Tensor(30, shape=(), dtype=int32)


In [19]:
print(tf.compat.v1.get_default_graph())

In [16]:
g = tf.Graph()
print(g)

In [18]:
g_1 = tf.compat.v1.get_default_graph()
print(g_1)